### ISSUE TITLE
Usage guide?

### ISSUE THREAD

**Issue by lifeofguenter** [inaturalist/elasticmaps#6]
It would be great to have any advice on how to use this with OSM (e.g. data-importer, other necessary configs)

**Comment by kueda** [comment]
elasticmaps is a Node-based mapserver that serves tiles from geodata stored in elasticsearch. If you wanted to use it to serve OSM data, you'd need to transfer some OSM data into elasticsearch, which is beyond the purview of this repo, though I expect you could write a script that uses [osmium](http://osmcode.org/) to read OSM data from an export and [post it to elasticearch](https://www.elastic.co/guide/en/kibana/current/tutorial-load-dataset.html).
